<button class="accordion"><div><span class="glyphicon glyphicon-menu-hamburger" style="font-size:24px;"></span><div class="acc_text">Navigator</div></div></button>
   <div class="panelDetail">
        <div class="col-md-12 category-flex cat-1">
            <div class="category-items-flex" id="cat-level-1">
                <?php foreach($categories as $cat) : ?>
                <div class="category-item" onclick="category_detail(1, '<?=$cat['id'] ?>', this);">
                    <input type="hidden" value="<?=$cat['id'] ?>">
                    <div><?=$cat['name'] ?></div>
                </div>    
                <?php endforeach ?>
            </div>
            <div class="category-items-arrow">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </div>

            <div class="category-items-flex" id="cat-level-2">

            </div>

            <div class="category-items-arrow">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </div>
            <div class="category-items-flex cat-3" id="cat-level-3">

            </div>
        </div>
   </div>


<div class="browse-contents">
    <div id="material-list">
        <div class="browse-list-title">
            Membranes
        </div>
        <?php foreach($membranes as $m) : ?>
        <div class="browse-list-item">
            <img src="files/icons/chevron-right.svg" style="width: 8px">
            <a class="list-item" id="tab<?=$m->id?>-tab" href="#tab<?=$m->id?>"><?=$m->idTag?></a>
        </div>
        <?php endforeach ?>
    </div>
    
    <div class="tab-contents">
        <?php foreach ($nonsec_membranes as $m) : ?>
        <div id="tab<?=$m->id?>">
            <div class="membraneName">
                <div>
                    <h2><?=$m->name?></h2>
                </div>
                <div class="membraneCategory">
                    <div class="categoryName"><?=$active_categories[$m->id]->category?></div>
                    <div class="categoryArrow"><span class="glyphicon glyphicon-chevron-right"></span></div>
                    <div class="categoryName"><?=$active_categories[$m->id]->subcategory?></div>
                </div> 
            </div>
            <div class="content"><?=$m->description?></div>
            <div class="content"><?=$m->references?></div>
            <button type="button" onclick="addSetToComparator('membrane', '<?=$m->id ?>')" style="margin-top: -15px;" class="btn btn-warning btn-sm pull-right">Add compounds to the comparator </button>
        </div>
        <?php endforeach ?>
    </div>
</div>

<script>
    $(document).ready(function() {
		$('#material-list').each(function() {

            var $active, $content, $links = $(this).find('a');

            $active = $($links[0]);
            $active.addClass('active');

            $content = $($active[0].hash);

            $links.not($active).each(function() {
                $(this.hash).hide();
            });

            $(this).on('click', 'a', function(e) {
                $active.removeClass('active');
                $content.hide();

                $active = $(this);
                $content = $(this.hash);

                $active.addClass('active');
                $content.show();

                e.preventDefault();
                setActive_category(this.id);
            });
		});
        document.getElementById("material-list").children[1].children[1].click();
});

var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].onclick = function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.maxHeight){
      panel.style.maxHeight = null;
    } else {
      panel.style.maxHeight = (panel.scrollHeight + 100) + "px";
    } 
  }
}
</script>

<script src="js/edit/membrane.js?ver=<?=JS_VERSION?>"></script>