<div id='chartdiv' style="height: 600px;"></div>

<div class="browse-contents">
    <div id="material-list">
        <div class="browse-list-title">
            Methods
        </div>
        <?= $nonsec_side_list ?>
    </div>

    <div class="tab-contents">
        <?php foreach($nonsec_methods as $m) : ?>
        <div id="tab<?=$m->id?>">
            <div class="membraneName">
                <div>
                    <h2><?=$m->name?></h2>
                </div>
                <div class="membraneCategory">
                    <div class="categoryName"><?=$active_categories[$m->id]->category?></div>
                    <div class="categoryArrow"><span class="glyphicon glyphicon-chevron-right"></span></div>
                    <div class="categoryName"><?=$active_categories[$m->id]->subcategory?></div>
                </div> 
            </div>
            <div class="content"><?=$m->description?></div>
            <div class="content"><?=$m->references?></div>
            <div class="content">
                <!-- <button type="button" onclick="addSetToComparator('method', '<?=$m->id?>')" style="margin-top: 15px;" class="btn btn-warning btn-sm pull-right">Add compounds to the comparator </button> -->
                <button type="button" onclick="redirect('search/method?id=<?= $m->id ?>')" style="margin-top: 15px;" class="btn btn-info btn-sm pull-right">Show compounds </button>
                <button type="button" onclick="redirect('export/method/<?= $m->id ?>')" style="margin-top: 15px; margin-right: 10px;" class="btn btn-danger btn-sm pull-right">Download data </button>
                <button type="button" onclick="add_method_to_downloader('<?= $m->id ?>', '<?= $m->name ?>');" style="margin-top: 15px; margin-right: 10px;" class="btn btn-warning btn-sm pull-right dwn-method-<?= $m->id ?>">Add to downloader </button>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>

<script src="js/browse.js?ver=<?=JS_VERSION?>"></script>
<script>
    var data = JSON.parse('<?= $nonsec_categories ?>');
    show_sunburst(data, "chartdiv");
</script>

<script>
    var remote_active = '<?= isset($_GET['target']) ? '#target_' . $_GET['target'] : '' ?>';

    $(document).ready(function() {
		$('#material-list').each(function() {
            var $active, $content, $links = $(this).find('a');

            $active = $($links[0]);
            $active.addClass('active');

            $content = $($active[0].hash);

            $links.not($active).each(function() {
                    $(this.hash).hide();
            });

            $(this).on('click', 'a', function(e) {

                $active.removeClass('active');
                $content.hide();

                $active = $(this);
                $content = $(this.hash);

                $active.addClass('active');
                $content.show();

                e.preventDefault();

                window.scrollTo({
                    top: 650,
                    left: 0,
                    behavior: 'smooth'
                });
            });
    });

    if(remote_active)
    {
        $(remote_active).click();
    }
});
</script>