<div class="browse-title">Datasets</div>
<script src="js/jquery-sortElements.js"></script>
<div class="publication-list">
    <input type="text" class="search" placeholder="Search..." id="publSearch" />
    <table class="publications" id="publications">
        <thead>
            <th>Authors</th>
            <th>Title</th>
            <th>Journal</th>
            <th>Year</th>
            <th>PMID/DOI</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php foreach($publications as $p) : ?>
                <tr data-id="<?= $p->id ?>" data-pmid="<?= $p->pmid ?>" data-doi="<?= $p->doi ?>" class="active">
                    <td>
                        <?php if($p->authors) : ?>
                        <?= $p->authors_short ?>
                        <div class="whisper">
                            <?= $p->authors ?>
                        </div>
                        <?php endif ?>
                    </td>
                    <td>
                        <?= $p->title_short ? $p->title_short : $p->citation_short?>
                        <whisper class="whisper">
                            <?= $p->citation ?>
                        </whisper>
                    </td>
                    <td><?= $p->journal ?></td>
                    <td><?= $p->year ?></td>
                    <td>
                        <?php if($p->pmid) : ?>
                            <?= $p->pmid ?>
                        <?php elseif($p->doi) : ?>
                            <?= $p->doi_short ?>
                        <?php endif ?>
                        <?php if($p->pmid || $p->doi) : ?>
                        <div class="whisper whisper-large">
                            <div class="pmid-whisper">
                                <?php if($p->pmid) : ?>
                                <div>
                                    <button class='orange'><a target="_blank" href="https://pubmed.ncbi.nlm.nih.gov/<?= $p->pmid ?>">Pubmed</a></button>
                                    <button class='blue'><a target="_blank" href="https://europepmc.org/article/MED/<?= $p->pmid ?>">EuropePMC</a></button>
                                </div>
                                <?php endif ?>
                                <?php if($p->doi) : ?>
                                <div>DOI: <a target="_blank" href="https://doi.org/<?= $p->doi ?>"><?= $p->doi ?></a></div>
                                <?php endif ?>
                            </div>
                        </div>
                        <?php endif ?>
                    </td>
                    <td id="hover-div">
                        <button title='Show data' class="blue" onclick="show_loader(); show_compounds('<?= $p->id?>');" ><?= Html::image('icons/mol.png') ?></button>
                        <button title='Export data' class="orange" onclick="redirect('export/publication/<?=$p->id?>');" ><?= Html::image('icons/cloud.png') ?></button>
                        <div class="whisper">
                            <table>
                                <tr>
                                    <td>Total substances:</td>
                                    <td><?= $p->total_substances ?></td>
                                </tr>
                                <tr>
                                    <td>Total passive interactions:</td>
                                    <td><?= $p->total_passive_interactions ?></td>
                                </tr>
                                <tr>
                                    <td>Total active interactions:</td>
                                    <td><?= $p->total_active_interactions ?></td>
                                </tr>
                            </table>
                        </div>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <div class="loading-bar animate" id="loading-bar">
    <span class="loading"></span>
    </div>
    <div class="table-suffix">
        <div class="table-paginator" id="paginator">
        </div>
        <div class="table-items-total">
            <element class="active">10</element>
            <element>25</element>
            <element>50</element>
            <element>100</element>
        </div>
    </div>
</div>

<script src="js/publications.js?ver=<?= JS_VERSION ?>">

</script>

<div style="display:none" id="content"> 
        <?php if(isset($list)) : ?>
            <div class="search-info">
                <h3><?= $publication->title ? $publication->title : $publication->citation ?></h3>
            </div>
        <div class="comp-addAll">
            <button type="button" onclick="download_dataset_byRef('<?=$publication->id?>')" class="btn btn-success btn-sm pull-right" style="margin-bottom: 5px;">Download dataset [.csv]</button>
            <button type="button" onclick="addSetToComparator('set', '<?=$publication->id?>')" class="btn btn-warning btn-sm pull-right" style="margin-bottom: 5px;">Add all compounds to the comparator </button>
            <button class="btn btn-sm btn-primary pull-right btn-add" id="btn-addALL">Add list to the comparator </button>
        </div>
            <ul class="search-ul" id="search-list">
                    <?php foreach ($list as $substance) : ?>
                    <li>
                            <div class="title">
                                <a href="/mol/<?= $substance->identifier?>"><?= $substance->name ?></a>
                                <button title="Add to comparator" id="<?= $substance->id ?>" type="button" class="btn btn-sm btn-primary btn-add">
                                    <span id="<?= $substance->name ?>" class="glyphicon glyphicon-plus"></span>
                                </button>
                            </div>
                            <div class="info">
                                <div class="info-text">
                                    <?php if($substance->MW != 0) : ?>
                                    <div><label><b>Molecular weight:</b></label> <?= $substance->MW ?> <br/></div>
                                    <?php else : ?>
                                    <div><label><b>Molecular weight:</b></label> N/A <br/></div>
                                    <?php endif ?>
                                    <div><label><b>SMILES:</b></label> <?= $substance->SMILES ?> <br/></div>
                                </div>
                                <div class="search-2DStructure" id="structure<?= $substance->id ?>"><script> update('<?= $substance->SMILES ?>', 'structure<?= $substance->id ?>');</script></div>
                            </div>
							<div class="flex-row space-between">
								<div class="references">
									<?php if($substance->pdb != '') : ?>
									<div class="ref"> <a href="https://www.rcsb.org/ligand/<?= $substance->pdb ?>" target="_blank">PDB </a></div>
									<?php endif ?>
									<?php if($substance->pubchem != '') : ?>
									<div class="ref"> <a target="_blank" href="https://pubchem.ncbi.nlm.nih.gov/compound/<?= $substance->pubchem ?>">PubChem </a></div>
									<?php endif ?>
									<?php if($substance->chEBI != '') : ?>
									<div class="ref"> <a target="_blank" href="http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:<?= $substance->chEBI ?>">chEBI </a></div>
									<?php endif ?>
									<?php if($substance->chEMBL != '') : ?>
									<div class="ref"> <a target="_blank" href="https://www.ebi.ac.uk/chembl/compound/inspect/<?= $substance->chEMBL ?>">chEMBL </a></div>
									<?php endif ?>
									<?php if($substance->drugbank != '') : ?>
									<div class="ref"> <a target="_blank" href="https://www.drugbank.ca/drugs/<?= $substance->drugbank ?>">DrugBank </a></div>
									<?php endif ?>
								</div>
								<div>
									<?php if(isset($_SESSION['user']) && $_SESSION['user']['admin'] == 1) : ?>
										<a class="extend"  href="/edit/compound/<?=$substance->id?>/<?=$substance->name?>">Edit</a>
									<?php endif ?>
								</div>
							</div>
                    </li>
                    <?php endforeach ?>
                </ul>
        <div class="text-center">   
            <ul class="pagination pagination-lg" id="paginator_comp" >
            <?php $count = $list_total ?>
              <?php for ($i=1; $i<($count/10)+1; $i++) : ?>
                <?php if($i == $pagination): ?>
                    <li class="active"id="activePag"><a href="/browse/sets/<?=$publication->id?>/<?=$i?>"><?=$i?></a></li>
                <?php else : ?>
                    <li><a href="/browse/sets/<?=$publication->id?>/<?=$i?>"><?=$i?></a></li>
                <?php endif ?>
              <?php endfor ?>
            </ul>
            <script>
            $(document).ready(function()
            {
                verifyPagination('paginator_comp');
            });
            </script>
        </div>
        <?php endif ?>
    </div>

<script src="js/searchEngine.js?<?=JS_VERSION?>" >
</script>