<button class="btn btn-success disabled btn-block"><span class="glyphicon glyphicon-user"></span>   Users editor</button>
<div><?=$nonsec_navigator?></div>
<div class="col-md-6 dataset-editor">
    <div class="col-md-11 o-card">
        <?=$nonsec_groups_table ?>
    </div>
</div>
<div class="col-md-6 dataset-editor">
    <div class="col-md-11 o-card">
        <?=$nonsec_users_table?>
    </div>
</div>

<script src="js/users.js?ver=<?=JS_VERSION?>"></script>