<?php

namespace App\Http\Controllers\Api\Public\V1;

use App\Http\Controllers\Api\Public\V1\Concerns\ListsInteractions;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Public\V1\SearchActiveInteractionsRequest;
use App\Http\Requests\Api\Public\V1\SearchPassiveInteractionsRequest;
use App\Http\Requests\Api\Public\V1\SearchStructureRequest;
use App\Http\Requests\Api\Public\V1\SimilarStructuresRequest;
use App\Http\Resources\Api\Public\V1\SimilarStructureResource;
use App\Http\Resources\Api\Public\V1\StructureResource;
use App\Models\Structure;
use App\Services\Interactions\PublicInteractionQuery;
use App\Services\Structures\Structure3dMolfile;
use App\Services\Structures\StructureIdentifierStatus;
use App\Support\PublicApiUrl;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Support\Str;

/**
 * Read-only, unauthenticated public API. Deliberately not sharing code with
 * App\Http\Controllers\StructureController — internal changes there must
 * never silently change this public contract.
 */
class StructureController extends Controller
{
    use ListsInteractions;

    public function index(SearchStructureRequest $request)
    {
        $filters = $request->filters();

        // Structures without an identifier yet (pending curation) can't be
        // fetched by any other public endpoint (all keyed by identifier) —
        // excluding them avoids listing dead-end records.
        $query = Structure::filter($filters)->whereNotNull('identifier');

        $structures = filled($filters['substructure'] ?? null)
            ? $query->simplePaginateFilter($request->perPage())
            : $query->paginateFilter($request->perPage());

        return StructureResource::collection($structures);
    }

    public function show(string $identifier)
    {
        $structure = $this->findStructure($identifier);
        $structure->load(['identifiers', 'parent', 'children']);

        return StructureResource::make($structure)->withDetails();
    }

    /**
     * Structures similar to this one (Tanimoto coefficient of Bingo
     * fingerprints), most similar first. Without a total: counting the
     * matches of a low threshold takes up to a second.
     */
    public function similar(string $identifier, SimilarStructuresRequest $request)
    {
        $structure = $this->findStructure($identifier);

        $similar = Structure::similarTo($structure->canonical_smiles, $request->threshold())
            ->whereNotNull('structures.identifier')
            ->whereKeyNot($structure->id)
            ->simplePaginate($request->perPage())
            ->withQueryString();

        return SimilarStructureResource::collection($similar);
    }

    /**
     * 3D structure as an MDL molfile, generated by RDKit on the first request.
     */
    public function molfile(string $identifier, Structure3dMolfile $molfiles)
    {
        $structure = $this->findStructure($identifier);

        $molfile = $molfiles->of($structure);

        abort_if($molfile === null, 422, 'The 3D structure could not be generated.');

        return response($molfile, 200, [
            'Content-Type' => Structure3dMolfile::CONTENT_TYPE,
            'Content-Disposition' => "inline; filename=\"{$structure->identifier}.mol\"",
        ]);
    }

    public function stats(string $identifier)
    {
        $structure = $this->findStructure($identifier);

        return response()->json([
            'data' => [
                'structure' => StructureResource::make($structure),
                'total' => [
                    'interactions_passive' => PublicInteractionQuery::total(PublicInteractionQuery::passive(['structure' => $structure->identifier])),
                    'interactions_active' => PublicInteractionQuery::total(PublicInteractionQuery::active(['structure' => $structure->identifier])),
                ],
            ],
        ]);
    }

    public function interactionsPassive(string $identifier, SearchPassiveInteractionsRequest $request)
    {
        $structure = $this->findStructure($identifier);

        return $this->passiveInteractions($request, ['structure' => $structure->identifier]);
    }

    public function interactionsActive(string $identifier, SearchActiveInteractionsRequest $request)
    {
        $structure = $this->findStructure($identifier);

        return $this->activeInteractions($request, ['structure' => $structure->identifier]);
    }

    /**
     * Identifiers are persistent: a merged one redirects (301) to the same
     * endpoint of the structure it was merged into, a removed one answers 410
     * with what is still known about it.
     */
    private function findStructure(string $identifier): Structure
    {
        $status = StructureIdentifierStatus::of($identifier);

        if ($status->status === StructureIdentifierStatus::ACTIVE) {
            return $status->structure;
        }

        if ($status->status === StructureIdentifierStatus::MERGED) {
            $path = Str::after(request()->path(), 'api/v1/');
            $target = preg_replace('#^structures/[^/]+#', 'structures/'.$status->replacedBy(), $path);
            $query = request()->getQueryString();

            throw new HttpResponseException(response()->json([
                'message' => "Structure {$identifier} was merged into {$status->replacedBy()}.",
                'data' => $status->toArray(),
            ], 301, ['Location' => PublicApiUrl::to($target).($query ? "?{$query}" : '')]));
        }

        if ($status->status === StructureIdentifierStatus::DELETED) {
            throw new HttpResponseException(response()->json([
                'message' => "Structure {$identifier} was removed from MolMeDB.",
                'data' => $status->toArray(),
            ], 410));
        }

        abort(404, 'Structure not found.');
    }
}
