<?php 
    $s = new Substances(45);
    $s2 = new Substances(436511);

    $s->identifier = 'MM00045';
    // $s->identifier = 'NN00045';
    $s->save(Validator_state::SOURCE_DRUGBANK);

    // echo (Rdkit::is_connected() ? 1 : 0);

    
    // $d = Rdkit::get_2d_structure($s);
    
    // echo (Rdkit::is_connected() ? 1 : 0);

    // print_r($d);
    die;

    // $v = Validator_duplicity::add($s, $s2, Validator_duplicity::DUPLICITY_DRUGBANK, 'DB0002', Validator_state::SOURCE_RDKIT, "DBBBB");
    // $v = Validator_attr_change::add($s, Validator_attr_change::FLAG_SMILES, 'COOOC', Validator_attr_change::SOURCE_DRUGBANK, 'jowak je pen');

    
    // $v = Validator_3D_structure::add($s, Validator_3D_structure::TYPE_3D_STRUCTURE_EDITED, Validator_state::SOURCE_CHEBI, new File(File::FOLDER_3DSTRUCTURES . 'MM00001.mol'), 
        // new File(File::FOLDER_3DSTRUCTURES . 'MM00002.mol'), NULL, "Další popis");

    // $v = Validator_fragmentation::add($s, Validator_fragmentation::TYPE_FRAGMENTED, 'jowak je pen dawd');

    // $v = Validator_state::instance(3471);

    // echo $v;

    die;
?>




<?php if(isset($_SESSION['user']) && $_SESSION['user']['admin'] == 1) : ?>
    <h4><a href="/edit/article"><div style="text-align: right;"> <span class="glyphicon glyphicon-edit"></span> Edit</div></a></h4>
<?php endif?>

<div><?=$nonsec_content?></div>

<script src="js/validator.js?ver=<?=JS_VERSION?>"></script>

