<?php if(session::is_admin()) : ?>
    <h4><a href="/edit/article"><div style="text-align: right;"> <span class="glyphicon glyphicon-edit"></span> Edit</div></a></h4>
<?php endif?>

<div><?=$nonsec_content?></div> 

<script src="js/validator.js?ver=<?=JS_VERSION?>"></script>
<script type="application/ld+json" >
    {
    "@context": "https://schema.org",
    "@id": "https://molmedb.upol.cz/detail/intro",
    "@type": "Dataset",
    "citation": [
        {
        "@id": "https://doi.org/10.1093/database/baz078",
        "url": "https://doi.org/10.1093/database/baz078",
        "@type": "CreativeWork"
        }
    ],
    "creator": [
        {
            "@type": "Person",
            "familyName": "Berka",
            "givenName": "Karel",
            "email": "karel.berka@upol.cz",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        },
        {
            "@type": "Person",
            "familyName": "Srejber",
            "givenName": "Martin",
            "email": "martin.srejber@upol.cz",
            "affiliation": "Palacky University in Olomouc, Krizkovskeho 511/8, 779 00, Olomouc, Czech Republic"
        },
        {
            "@type": "Person",
            "familyName": "Bazgier",
            "givenName": "Vaclav",
            "email": "vaclav.bazgier@upol.cz",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        },
        {
            "@type": "Person",
            "familyName": "Juracka",
            "givenName": "Jakub",
            "email": " jakub.juracka55@gmail.com",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        },
        {
            "@type": "Person",
            "familyName": "Storchmannova",
            "givenName": "Katerina",
            "email": "katerina.storchmannova@upol.cz",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        },
        {
            "@type": "Person",
            "familyName": "Martinat",
            "givenName": "Dominik",
            "email": "dominik.martinat@upol.cz",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        },
        {
        "@type": "Person",
        "familyName": "Jaromerska",
        "givenName": "Michaela",
        "email": "michaela.jaromerska@upol.cz",
        "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
    },
    {
        "@type": "Person",
        "familyName": "Galgonek",
        "givenName": "Jakub",
        "email": "jakub.galgonek@uochb.cas.cz",
        "affiliation": "Institute of Organic Chemistry and Biochemistry of the CAS, Flemingovo namesti 2, 166 10, Prague 6, Czech Republic"
    }
    ],
    "dct:conformsTo": "https://bioschemas.org/profiles/Dataset/1.0-RELEASE",
    "description": "MolMeDB is an open chemistry database about interactions of molecules with membranes or transporters. \"Open\" means that you can send your scientific data to MolMeDB and that others may use it. We collect information on how chemicals interact with individual membranes or transporters either from experiment or from simulations. ",
    "distribution": [
        {
        "@id": "https://molmedb.upol.cz/media/files/download/stats/active_passive_interactions.zip",
        "@type": "DataDownload",
        "contentUrl": "https://molmedb.upol.cz/media/files/download/stats/active_passive_interactions.zip",
        "encodingFormat": "text/csv"
        },
        {
        "@id": "https://drive.google.com/file/d/1HNyMr44UVLXS8UYiX6ZiNE4WArxMKved/view?usp=sharing",
        "@type": "DataDownload",
        "contentUrl": "https://drive.google.com/file/d/1HNyMr44UVLXS8UYiX6ZiNE4WArxMKved/view?usp=sharing",
        "encodingFormat": "application/rdf+xml"
        },
        {
        "@id": "https://drive.google.com/file/d/1a7EmlB0vszXrzGykNMV7CuoFdAIcDXW0/view?usp=sharing",
        "@type": "DataDownload",
        "contentUrl": "https://drive.google.com/file/d/1a7EmlB0vszXrzGykNMV7CuoFdAIcDXW0/view?usp=sharing",
        "encodingFormat": "text/turtle"
        },
        {
        "@id": "https://drive.google.com/file/d/1LSWqv1nOGRyzlxNcNXR0osaVJXWT9sE6/view?usp=sharing",
        "@type": "DataDownload",
        "contentUrl": "https://drive.google.com/file/d/1LSWqv1nOGRyzlxNcNXR0osaVJXWT9sE6/view?usp=sharing",
        "encodingFormat": "application/n-triples"
        }
    ],
    "identifier": [
        "https://molmedb.upol.cz/"
    ],
    "isAccessibleForFree": [
        true
    ],
    "keywords": [
        {
        "@id": "http://semanticscience.org/resource/SIO_000750",
        "@type": "DefinedTerm"
        },
        {
        "@id": "http://www.bioassayontology.org/bao# BAO_0000283",
        "@type": "DefinedTerm"
        },
        {
        "@id": "http://www.bioassayontology.org/bao# BAO_0002182",
        "@type": "DefinedTerm"
        },
        {
        "@id": "http://www.bioassayontology.org/bao# BAO_0003008",
        "@type": "DefinedTerm"
        },
        {
        "@id": "https://rdf.molmedb.upol.cz/vocabulary#MembraneModel",
        "@type": "DefinedTerm"
        },
        {
        "@id": "http://www.bioassayontology.org/bao#BAO_0003043",
        "@type": "DefinedTerm"
        }
    ],
    "license": {
        "@id": "https://creativecommons.org/licenses/by/4.0/",
        "@type": "CreativeWork",
        "url": "https://creativecommons.org/licenses/by/4.0/"
    },
    "maintainer": [
        {
            "@type": "Person",
            "familyName": "Berka",
            "givenName": "Karel",
            "email": "karel.berka@upol.cz",
            "affiliation": "Palacky University in Olomouc, Faculty of Science, Department of Physical Chemistry, tr. 17. listopadu 1192/12, 779 00, Olomouc, Czech Republic"
        }
    ],
    "name": "MolMeDB: Molecules on Membranes Database",
    "publisher": [
        {
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": "https://www.upol.cz",
        "url": "https://www.upol.cz",
        "name": "Palacky University Olomouc"
        }
    ],
    "url": "https://molmedb.upol.cz/"
    }
</script >

