
<div class="col-md-5 col-sm-12 uploadTableDiv">
        <h4 style="text-align: center;"><b>Link records</b></h4>
        
        <form method="post" enctype="multipart/form-data">
            <label>ID substance (1)</label><br/>    
            <input class="form-control" name="id1" placeholder="First ID" type="text" autocomplete="false"/><br/>
            <label>ID substance (2)</label><br/>
            <input class="form-control" name="id2" placeholder="Second ID" type="text" autocomplete="false"/>
            <button style="margin-top:20px;" type="submit" class="btn btn-primary btn-sm pull-right">Link ligands</button>
        </form>
        
    </div>