<div class="centering" >
    <div class="l-card">
        <div class="login-title">Please, log in:</div>
        <form method="post">
            <div class="form-group">
                <label for="usr">Login</label>
                <input type="text" class="form-control" name="name" />
                <label for="pwd">Password</label>
                <input type="password" class="form-control" name="password" />
                <div class="login-last-row">
                    <!-- <p class="pull-left" style="margin-top: 5px;"> <a href="/signup"><span class="glyphicon glyphicon-user"></span> Create new account</a></p> -->
                    <button type="submit" class="btn btn-info btn-sm pull-right">Login</button>
                </div>
            </div>

        </form>
    </div>
</div>



