<datalist id="search-datalist"></datalist>
<datalist id="search-datalist-smiles"></datalist>

<h3><b>Search compounds by:</b></h3>
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#compound">Name</a></li>
  <li><a data-toggle="tab" href="#membrane">Membrane</a></li>
  <li><a data-toggle="tab" href="#method">Method</a></li>
  <li><a data-toggle="tab" href="#smiles">SMILES</a></li>
  <li><a data-toggle="tab" href="#transporters">Transporters</a></li>
  <!-- <li><a data-toggle="tab" href="#uniprot">Uniprot ID</a></li> -->
</ul>

<div class="tab-content">
  <div id="compound" class="tab-pane fade in active">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Search by name</div>
        <div class="panel-body">

          <form method="get" action="/search/compound/1" autocomplete="off">
            <div class="autocomplete">
              <input class="searchEngine" type="text" name="q" placeholder="Search compounds (e.g. Caffeine)" id="compoundSearch">
            </div>
            <button type="submit" class="btn btn-success pull-right">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div id="membrane" class="tab-pane fade in ">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Membranes</div>
        <div class="panel-body">
          <div id='membranechartdiv' style="height: 600px;"></div>
        </div>
      </div>
    </div>
  </div>

  <div id="method" class="tab-pane fade in ">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Methods</div>
        <div class="panel-body">
          <div id='methodchartdiv' style="height: 600px;"></div>
        </div>
      </div>
    </div>
  </div>
  <div id="smiles" class="tab-pane fade">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Search compounds by SMILES</div>
        <div class="panel-body">
          <form method="get" action="/search/smiles/1" autocomplete="off">
            <div class="autocomplete">
              <input type="text" class="searchEngine" name="q" id='smilesSearch' placeholder="Search compounds by SMILES">
            </div>
            <button type="submit" class="btn btn-success pull-right">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div id="transporters" class="tab-pane fade">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Search compounds by transporter targets</div>
        <div class="panel-body">
          <form method="get" action="/search/transporter/1" autocomplete="off">
            <div class="autocomplete">
              <input type="text" class="searchEngine" name="q" id='transporterSearch' placeholder="Search compounds by transporter">
            </div>
            <button type="submit" class="btn btn-success pull-right">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- <div id="uniprot" class="tab-pane fade">
    <div class="panel-group">
      <div class="panel panel-primary">
        <div class="panel-heading">Search compounds by uniprot ID</div>
        <div class="panel-body">
          <form method="get" action="/search/uniprot/1" autocomplete="off">
            <div class="autocomplete">
              <input type="text" class="searchEngine" name="q" id='uniprotSearch' placeholder="Search compounds by uniprot ID">
            </div>
            <button type="submit" class="btn btn-success pull-right">Search</button>
          </form>
        </div>
      </div>
    </div>
  </div> -->

</div>

<?php if ($show_detail) : ?>
  <div class="search-info">
    <h3><?= $nonsec_info ?></h3>
  </div>
  <div id="loader"></div>

  <div style="display:none" id="content">
    <?php if (isset($list)) : ?>
      <div class="comp-addAll"><button class="btn btn-sm btn-primary pull-right btn-add" id="btn-addALL">Add list to the comparator </button></div><br />
      <ul class="search-ul">
        <?php foreach ($list as $substance) : ?>
          <li>
            <div class="flex-column space-between" style="height: -webkit-fill-available;">
              <div>
                <div class="title">
                  <a href="/mol/<?= $substance->identifier ?>"><?= $substance->name ?></a>
                  <button title="Add to comparator" id="<?= $substance->id ?>" type="button" class="btn btn-sm btn-primary btn-add">
                    <span id="<?= $substance->name ?>" class="glyphicon glyphicon-plus"></span>
                  </button>
                </div>
                <div class="info">
                  <div class="info-text">
                    <?php if (isset($substance->altername) && $substance->altername != '') : ?>
                      <div><label><b>Alternative name:</b></label> <?= $substance->altername ?> <br /></div>
                    <?php endif ?>
                    <?php if ($substance->MW != 0) : ?>
                      <div><label><b>Molecular weight:</b></label> <?= $substance->MW ?> <br /></div>
                    <?php else : ?>
                      <div><label><b>Molecular weight:</b></label> N/A <br /></div>
                    <?php endif ?>
                    <div><label><b>SMILES:</b></label> <?= $substance->SMILES ?> <br /></div>
                  </div>
                  <div class="search-2DStructure" id="structure<?= $substance->id ?>">
                    <script>
                      update('<?= $substance->SMILES ?>', 'structure<?= $substance->id ?>');
                    </script>
                  </div>
                </div>
              </div>
              <div class="flex-row space-between">
                <div class="references">
                  <?php if ($substance->pdb != '') : ?>
                    <div class="ref"> <a href="https://www.rcsb.org/ligand/<?= $substance->pdb ?>" target="_blank">PDB </a></div>
                  <?php endif ?>
                  <?php if ($substance->pubchem != '') : ?>
                    <div class="ref"> <a target="_blank" href="https://pubchem.ncbi.nlm.nih.gov/compound/<?= $substance->pubchem ?>">PubChem </a></div>
                  <?php endif ?>
                  <?php if ($substance->chEBI != '') : ?>
                    <div class="ref"> <a target="_blank" href="http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:<?= $substance->chEBI ?>">chEBI </a></div>
                  <?php endif ?>
                  <?php if ($substance->chEMBL != '') : ?>
                    <div class="ref"> <a target="_blank" href="https://www.ebi.ac.uk/chembl/compound/inspect/<?= $substance->chEMBL ?>">chEMBL </a></div>
                  <?php endif ?>
                  <?php if ($substance->drugbank != '') : ?>
                    <div class="ref"> <a target="_blank" href="https://www.drugbank.ca/drugs/<?= $substance->drugbank ?>">DrugBank </a></div>
                  <?php endif ?>
                </div>
                <div>
                  <?php if (isset($_SESSION['user']) && $_SESSION['user']['admin'] == 1) : ?>
                    <a class="extend" href="/edit/compound/<?= $substance->id ?>/<?= $substance->name ?>">Edit</a>
                  <?php endif ?>
                </div>
              </div>
            </div>
          </li>
        <?php endforeach ?>
      </ul>
    <?php endif ?>
  </div>

  <div class="col-md-1"></div>

<?php endif ?>


<script src="https://cdn.amcharts.com/lib/5/index.js"></script>
<script src="https://cdn.amcharts.com/lib/5/hierarchy.js"></script>
<script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
<script>
  $(document).ready(function() 
  {
    setTimeout(showContent, 1000);
  });

  function showContent() {
    if (<?= $show_detail ?>) {
      document.getElementById("content").style.display = "flex";
      document.getElementById("loader").style.display = "none";
    }
  }

function show_sunburst(data, target_id, ontap)
{
    am4core.ready(function() {
        // Themes begin
        am4core.useTheme(am4themes_animated);
        // Themes end
    
        // create chart
        var chart = am4core.create(target_id, am4plugins_sunburst.Sunburst);
        chart.padding(0,0,0,0);
        chart.radius = am4core.percent(98);
    
        chart.data = data;
    
        chart.colors.step = 2;
        chart.fontSize = 11;
        chart.innerRadius = am4core.percent(10);
    
        // define data fields
        chart.dataFields.value = "value";
        chart.dataFields.name = "name";;
        chart.dataFields.children = "children";
    
    
        var level0SeriesTemplate = new am4plugins_sunburst.SunburstSeries();
        level0SeriesTemplate.hiddenInLegend = false;
        chart.seriesTemplates.setKey("0", level0SeriesTemplate)
        level0SeriesTemplate.labels.template.text = "{category}";
        level0SeriesTemplate.slices.template.tooltipText = "{category}";
    
        // this makes labels to be hidden if they don't fit
        level0SeriesTemplate.labels.template.truncate = true;
        level0SeriesTemplate.labels.template.hideOversized = true;
    
        level0SeriesTemplate.labels.template.adapter.add("rotation", function(rotation, target) {
            target.maxWidth = target.dataItem.slice.radius - target.dataItem.slice.innerRadius - 10;
            target.maxHeight = Math.abs(target.dataItem.slice.arc * (target.dataItem.slice.innerRadius + target.dataItem.slice.radius) / 2 * am4core.math.RADIANS);
    
            return rotation;
        })

        level0SeriesTemplate.slices.template.events.on('hit', function(ev)
        {
            var el_id = ev.target.dataItem.sunburstDataItem._dataContext.id_element;
            var last = ev.target.dataItem.sunburstDataItem._dataContext.last;

            if(!last)
            {
                return;
            }
            
            if(!el_id)
            {
                console.log("Element id not found");
                return false;
            }

            ontap(el_id);
        });
    
    
        var level1SeriesTemplate = level0SeriesTemplate.clone();
        chart.seriesTemplates.setKey("1", level1SeriesTemplate)
        level1SeriesTemplate.fillOpacity = 0.75;
        level1SeriesTemplate.hiddenInLegend = true;
        // level1SeriesTemplate.labels.template.text = "{category}";
    
        var level2SeriesTemplate = level0SeriesTemplate.clone();
        chart.seriesTemplates.setKey("2", level2SeriesTemplate)
        level2SeriesTemplate.fillOpacity = 0.5;
        level2SeriesTemplate.hiddenInLegend = true;
        // level2SeriesTemplate.labels.template.text = "{category}";
        level2SeriesTemplate.labels.template.fill = am4core.color("#000");
        chart.legend = new am4charts.Legend();
    
    }); 
}
var mem_data = JSON.parse('<?= $nonsec_membrane_categories ?>');
show_sunburst(mem_data, "membranechartdiv", (id) => {
  redirect("search/membrane?id=" + id)
});
var met_data = JSON.parse('<?= $nonsec_method_categories ?>');
show_sunburst(met_data, "methodchartdiv", (id) => {
  redirect("search/method?id=" + id)
});

</script>

<script src="js/searchEngine.js?<?=JS_VERSION?>" >
</script>