<div class="centering" >
    <div class="l-card">
        <div class="login-title">Please, log in:</div>
        <form method="post" class="">
            <div class="form-group">
                <label for="usr">Username</label>
                <input type="text" class="form-control" name="name" />
                <label for="pwd">Password</label>
                <input type="password" class="form-control" name="password" />
                <label for="pwd">Confirm password:</label>
                <input type="password" class="form-control" name="passwordConfirm" />
                <label for="pwd">Current year: (antispam)</label>
                <input type="text" class="form-control" name="year" />
                <div class="login-last-row">
                    <button type="submit" class="btn btn-info btn-sm pull-right">SignUp</button>
                </div>
            </div>

        </form>
    </div>
</div>



