<div class="stats">
    <div class="stats-total">
        <div class="stats-title">
            Statistics
        </div>
        
        <div class="stats-total-grid">
            <div class="stats-total-grid-item">
                <div class="stats-total-grid-item-top">
                    <div>
                        <div>Total interactions</div>
                        <div><?= $interactions->total ?></div>
                    </div>
                    <div>
                        <?= Html::image('icons/interaction.png', "stat-panel-img") ?>
                    </div>
                </div>

            </div>
            <div class="stats-total-grid-item">
                <div class="stats-total-grid-item-top">
                    <div>
                        <div>Total substances</div>
                        <div><?= $substances->total ?></div>
                    </div>
                    <div>
                        <?= Html::image('icons/molecule.png', "stat-panel-img") ?>
                    </div>
                </div>

            </div>
            <div class="stats-total-grid-item">
                <div class="stats-total-grid-item-top">
                    <div>
                        <div>Total membranes</div>
                        <div><?= $membranes->total ?></div>
                    </div>
                    <div>
                        <?= Html::image('icons/lipid.png', "stat-panel-img") ?>
                    </div>
                </div>

            </div>
            <div class="stats-total-grid-item">
                <div class="stats-total-grid-item-top">
                    <div>
                        <div>Total methods</div>
                        <div><?= $methods->total ?></div>
                    </div>
                    <div>
                        <?= Html::image('icons/microscope.png', "stat-panel-img") ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="stats-rows">
        <div class="stats-row stats-row-1">
            <div class="stat-panel" style="width: 60%">
                <div class="stat-panel-title">Growth curve</div>
                <div class="stat-panel-subtitle">Increase in the amount of data by date</div>
                <div id="interactionAddDiv" class="stat-chart" style="width: 100%; height: 560px;"></div>
            </div>
            <div class="stats-column" style="width: 38%">
                <div class="stat-panel">
                    <div class="stat-panel-title">Proportion of interaction types</div>
                    <div id="interactionAddDiv2" style="width: 100%; height: 210px;"></div>
                </div>
                <div class="stat-panel">
                    <div class="stat-panel-title">Links to external databases</div>
                    <div id="interactionAddDiv3" class="stat-panel" style="width: 100%; height: 300px;"></div>
                </div>
            </div>
        </div>

        <div class="stats-row">
            <div class="stat-panel" style="width: 100%">
                <div class="stat-panel-title">Methods</div>
                <div class="stat-panel-subtitle">Amount of data</div>
                <div id="methodDiv" class="stat-chart" style="width: 100%; height: 560px;"></div>
            </div>
        </div>

        <div class="stats-row">
            <div class="stat-panel" style="width: 100%">
                <div class="stat-panel-title">Membranes</div>
                <div class="stat-panel-subtitle">Amount of data</div>
                <div id="membraneDiv" class="stat-chart" style="width: 100%; height: 560px;"></div>
            </div>
        </div>
    </div>
</div>

<script src="js/amcharts64/themes/animated.js"></script>
<script src="js/stats.js"></script>

<script>
    $(".main-page").css('padding', '0');
    var inter_adding_data = JSON.parse('<?= json_encode($interactions->adding->data) ?>');
    var inter_adding_params = {
        axisBreaks: JSON.parse('<?= json_encode($interactions->adding->axisBreaks)?>'),
        series: [ 
            {
                attribute: 'count_interactions',
                label: 'Total interactions'
            },
            {
                attribute: 'count_substances',
                label: "Total substances"
            }
        ]
    };
    makeAddingLineChart(inter_adding_data, "interactionAddDiv", inter_adding_params)

    var data = JSON.parse('<?= json_encode($identifiers->data) ?>');
    var axisBreak = JSON.parse('<?= json_encode($identifiers->axisBreaks[0])?>');
    var max_value = parseInt('<?= $identifiers->maxValue ?>');
    make_identifiers_chart("interactionAddDiv3", data, axisBreak, max_value);

    // Chart for count of total membranes
    var data = JSON.parse('<?= json_encode($membranes->stats->data) ?>');
    var axisBreaks = {
        interactions: JSON.parse('<?= json_encode($membranes->stats->axisBreaks_interactions)?>')
    }

    make_membrane_total_column_chart('membraneDiv', data);

    // Chart for count of total methods
    var data = JSON.parse('<?= json_encode($interactions_pa->data) ?>');
    makeInteractionsPie('interactionAddDiv2', data);

    var data = JSON.parse('<?= json_encode($methods->stats->data) ?>');
    var axisBreaks = {
        interactions: JSON.parse('<?= json_encode($methods->stats->axisBreaks_interactions)?>')
    }

    make_method_total_column_chart('methodDiv', data, axisBreaks);
</script>