<h1 style="text-align: center">Uploader</h1>


    <div id="dataupload_modal" class="modal">

      <div class="modal-content">
        <span class="close" id="dataupload_close">&times;</span>
        <div id="table" class="uploadedTable"></div> 
      </div>

    </div>


 <script>
    CKEDITOR.replace( 'descript' );
    CKEDITOR.replace( 'references' );
</script>
<script src="../js/parseFile.js?ver=<?=JS_VERSION?>">
    
</script>