<h2 style='text-align: center;'><b>Join molecules</b></h2>

<div class="col-md-6">
    <form method="post">
        <label>First substance ID</label><br/>
        <input class="form-control" type="text" name="substance_1"><br/>
        <label>Second substance ID</label><br/>
        <input class="form-control" type="text" name="substance_2"><br/>
        <button class="btn btn-sm btn-success pull-right">Join</button>
    </form>
</div>