<h2 style="font-weight: bold; text-align: center;">Data validator</h2>

<div class='col-md-12 row justify-content-center'>
    <div class='row justify-content-start align-items-center'>
        <div style='font-weight: bold; margin-right: 10px;'>
            States: 
        </div>
        <?php foreach(Validator::$enum_states as $id => $val): ?>
            <div style='color:green; font-weight:bold; margin-right: 20px;'>
                <?= "$id - $val" ?>
            </div>
        <?php endforeach ?>
    </div>
</div>

<div class='col-md-12' style="margin-bottom: 50px;"> 
    <div class='col-md-6'>
        <h4>Remains to validate (<?= count($compounds) ?>)</h4>
        <div style='max-height: 400px; overflow-y:auto;'>
            <table class='table'>
                <thead>
                    <td><b>ID</b></td>
                    <td><b>Name</b></td>
                    <td><b>State</b></td>
                    <td><b>Errors</b></td>
                    <td><b>Action</b></td>
                </thead>
                <tbody>
                    <?php foreach($compounds as $c) : ?>
                    <tr>
                        <td><?= $c->identifier ? Html::anchor('mol/' . $c->identifier, $c->id, true) : $c->id  ?></td>
                        <td><?= $c->name ?></td>
                        <td><?= $c->validated ?></td>
                        <td><?= $c->errors ?></td>
                        <td><button type='button' onclick='redirect("validator/show/<?=$c->id ?>")' class='btn btn-sm btn-warning'>Show</button></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class='col-md-6'>
        <?php if($detail && count($detail)) : ?>
            <h2><?= $detail[0]->name ?></h2>
            <h4>Compound reports</h4>
            <div style='max-height: 400px; overflow-y:auto;'>
                <table class='table'>
                    <thead>
                        <td><b>Id substance</b></td>
                        <td><b>Datetime</b></td>
                        <td><b>Actions</b></td>
                        <td><b>Message</b></td>
                    </thead>
                    <tbody>
                        <?php foreach($detail as $d) : ?>
                        <tr>
                            <td><?= !$d->identifier_2 ? '' : Html::anchor('mol/' . $d->identifier_2, $d->identifier_2, true) ?></td>
                            <td><?= date('d.m.Y H:i', strtotime($d->datetime)) ?></td>
                            <td>
                                <?php if($d->identifier_2) : ?> 
                                <button type='button' onclick="alert_window('Are you sure you want to join molecules (<?= $d->id . ', ' . $d->id_substance_2 ?>)?', 'validator/join/<?=$d->id ?>/<?= $d->id_substance_2 ?>', false)" class='btn btn-sm btn-danger'>Join</button>
                                <?php endif ?>
                            </td>
                            <td><?= "$d->duplicity" ?></td>
                        </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        <?php endif ?>
    </div>
</div>

<div class='col-md-12'>
    <div class='col-md-6'>
        <h4>Last scheduler runs</h4>
        <div style='max-height: 400px; overflow-y:auto;'>
            <table class='table'>
                <thead>
                    <td><b>ID</b></td>
                    <td><b>Datetime</b></td>
                    <td><b>Error/Success</b></td>
                    <td><b>Action</b></td>
                </thead>
                <tbody>
                    <?php foreach($reports as $r) : ?>
                    <tr>
                        <td><?= $r->id ?></td>
                        <td><?= date('d.m.Y H:i', strtotime($r->datetime)) ?></td>
                        <td><?= "$r->error_count/$r->success_count" ?></td>
                        <td>
                            <?php if($r->report_path) : ?>
                            <button type='button' onclick='redirect("<?=$r->report_path ?>")' class='btn btn-sm btn-success'>Download report</button>
                            <?php endif ?>
                        </td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<script src="js/validator.js?ver=<?=JS_VERSION?>"></script>