<button class="btn btn-success disabled btn-block"><span class="glyphicon glyphicon-pencil"></span>   Membrane editor</button>
<div><?=$nonsec_navigator?></div>


<div class="col-md-12 content category-flex cat-1">
    <div class="category-items-flex" id="cat-level-1">
        <?php foreach($categories as $cat) : ?>
        <div class="category-item" onclick="category_detail(1, '<?=$cat['id'] ?>', this);">
            <input type="hidden" value="<?=$cat['id'] ?>">
            <?=$cat['name'] ?>
        </div>    
        <?php endforeach ?>
    </div>
    <div class="category-items-arrow">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </div>
    
    <div class="category-items-flex" id="cat-level-2">
        
    </div>
    
    <div class="category-items-arrow">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </div>
    <div class="category-items-flex cat-3" id="cat-level-3">

    </div>
</div>

<div class="col-md-12 content o-card" style="background-color: #f9f9f9">
    <form  method="post" action="/edit/membrane/<?=EditController::T_CATEGORY?>/">
        <h2>Edit category</h2>
        <table class="dataset-table">
            <tr>
                <td><b>Choose membrane: </b></td>
                <td>
                    <select name="id">
                        <?php foreach($membranes as $mem) : ?>
                        <option value="<?=$mem->id ?>"><?=$mem->name?></option>
                        <?php endforeach ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td><b>Choose category: </b></td>
                <td>
                    <select name="category_id">
                        <?php foreach($categories as $cat) : ?>
                        <option value="<?=$cat->id ?>"><?=$cat->name?></option>
                        <?php endforeach ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td><b>Choose subcategory: </b></td>
                <td>
                    <select name="subcategory_id">
                        <?php foreach($subcategories as $cat) : ?>
                        <option value="<?=$cat->id ?>"><?=$cat->name?></option>
                        <?php endforeach ?>
                    </select>
                </td>
            </tr>
        </table>
        <button type="submit" class="btn btn-sm btn-success pull-right">Save</button>
    </form>
</div>


<script src="js/edit/membrane.js?ver=<?=JS_VERSION?>"></script>