<base href="<?= Url::base() . MEDIA_ROOT ?>" />
<link rel="stylesheet" href="css/bootstrap.min.css"/>
<link rel="stylesheet" href="css/LiteMol-plugin.min.css">
<link rel="stylesheet" href="css/style.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/tree.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/tables.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/layout.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/flexbox.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/depict.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/stats.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/searchEngine.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<link rel="stylesheet" href="css/browse.css?ver=<?=CSS_VERSION?>" type="text/css"/>
<style>
    body{
        background-image: none !important;
    }
</style>

<div class="general-info">
    <p class="compoundTitle">
        <?= $substance->name ?>
    </p>
    <div style="display:flex; flex-direction:column; justify-content: start; flex-wrap: wrap;">
        <div class="general-info" style="margin-right: 20px;">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <td>
                            <b style="color: #4a82da">General info</b>
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><b>Identifier</b></td>
                        <td><?= $data->detail['identifiers']['molmedb'] ?></td>
                    </tr>
                    <tr>
                        <td><b>Molecular weight</b></td>
                        <td><?= $data->detail['molecular_weight'] ?></td>
                    </tr>
                    <tr>
                        <td><b>LogP</b></td>
                        <td><?= $data->detail['logp'] ?></td>
                    </tr>
                    <tr>
                        <td><b>Names</b></td>
                        <td><?= implode(', ', $data->detail['identifiers']['name']) ?></td>
                    </tr>
                    <tr>
                        <td><b>Pubchem IDs</b></td>
                        <td><?= implode(', ', $data->detail['identifiers']['pubchem']) ?></td>
                    </tr>
                    <tr>
                        <td><b>PDB IDs</b></td>
                        <td><?= implode(', ', $data->detail['identifiers']['pdb']) ?></td>
                    </tr>
                    <tr>
                        <td><b>Drugbank IDs</b></td>
                        <td><?= implode(', ', $data->detail['identifiers']['drugbank']) ?></td>
                    </tr>
                    <tr>
                        <td><b>ChEMBL IDs</b></td>
                        <td><?= implode(', ', $data->detail['identifiers']['chembl']) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <?php if(isset($data['passive_interactions'])) : ?>
        <div class="general-info">
            <b style="font-size:15px; color: #4a82da">Passive interactions</b>
            <?php 
                // HTML content template
                $t = new Table([
                    Table::S_PAGINATIOR_POSITION => 'left',
                    Table::FILTER_HIDE_COLUMNS => TRUE,
                    Table::FILTER_HIDE_COLUMNS_DEFAULT => true,
                    Table::S_NODATA => "No data found..."
                ]);

                $t->column('Membrane.name')
                    ->numeric()
                    ->link('browse/membranes?target=', 'membrane_id')
                    ->css(array
                    (
                        'text-align' => 'center' // Centering - flex - justify-content: center;
                    ))
                    ->title('Membrane');

                $t->column('Method.name')
                    ->numeric()
                    ->link('browse/methods?target=', 'method_id')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->title('Method');

                $t->column('charge')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->numeric()
                    ->title('Q', 'Charge');

                $t->column('Temperature.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ), true)
                    ->title('T <br/><label class="units">[°C]</label>', "Temperature"); 

                $t->column('Xmin.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('Position_acc')
                    ->title('X<sub>min</sub> <br/><label class="units">[nm]</label>', "Position of minima along the membrane normal from the membrane center");

                $t->column('Gpen.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('Penetration_acc')
                    ->title('&Delta;G<sub>pen</sub> <br/><label class="units">[kcal / mol]</label>', "Penetration barrier (maximum - minimum)");

                $t->column('Gwat.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('Water_acc')
                    ->title('&Delta;G<sub>wat</sub> <br/><label class="units">[kcal / mol]</label>', "A depth of minima within membrane");

                $t->column('LogK.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('LogK_acc')
                    ->title('LogK<sub>m</sub> <br/><label class="units">[mol<sub>m</sub>/mol<sub>w</sub>]</label>', "Partition coefficient membrane/water");

                $t->column('LogPerm.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('LogPerm_acc')
                    ->title('LogPerm <br/><label class="units">[cm/s]</label>', "Permeability coefficient");

                $t->column('Theta.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('theta_acc')
                    ->title('Theta<br/><label class="units">[°]</label>', "Contact angle in membrane");

                $t->column('Abs_wl.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('abs_wl_acc')
                    ->title('Abs_wl<br/><label class="units">[nm]</label>', "Peak absorption wavelenght");

                $t->column('Fluo_wl.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('fluo_wl_acc')
                    ->title('Fluo_wl<br/><label class="units">[nm]</label>', "Peak fluorescence wavelenght");

                $t->column('QY.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('qy_acc')
                    ->title('QY<br/><label class="units"></label>', "Quantum yield");

                $t->column('lt.value')
                    ->css(array
                    (
                        'text-align' => 'center'
                    ))
                    ->accuracy('lt_acc')
                    ->title('lt<br/><label class="units">[ns]</label>', "Fluorescence lifetime");

                $t->column('Note')
                    ->long_text()
                    ->title('Note');

                $t->column('References.primary')
                    ->long_text()
                    ->title('Primary<br/> reference', "Original source");

                $t->column('References.secondary')
                    ->long_text()
                    ->title('Secondary<br/> reference', "Source of input into databse if different from original");

                $t->datasource($data['passive_interactions']);

                echo $t->html();
            ?>
        </div>
        <?php endif ?>
    </div>
    <?php if(isset($data['active_interactions'])) : ?>
    <div class="general-info">
        <b style="font-size:15px; color: #4a82da">Active interactions</b>
        <?php 
            // HTML content template
            $t = new Table([
                Table::S_PAGINATIOR_POSITION => 'left',
                Table::FILTER_HIDE_COLUMNS => TRUE,
                Table::FILTER_HIDE_COLUMNS_DEFAULT => false,
                Table::S_NODATA => "No data found..."
            ]);

            $t->column('Target.Name')
                ->numeric()
                ->css(array
                (
                    'text-align' => 'center' // Centering - flex - justify-content: center;
                ))
                ->title('Target');

            $t->column('Target.Uniprot_id')
                ->numeric()
                ->css(array
                (
                    'text-align' => 'center'
                ))
                ->title('Uniprot ID');

            $t->column('Type')
                ->css(array
                (
                    'text-align' => 'center'
                ))
                ->numeric()
                ->title('Type');

            $t->column('Note')
                ->long_text()
                ->title('Note');

            $t->column('pKm')
                ->numeric()
                ->title('pKm');
            $t->column('pKi')
                ->numeric()
                ->title('pKi');
            $t->column('pEC50')
                ->numeric()
                ->title('pEC50');
            $t->column('pIC50')
                ->numeric()
                ->title('pIC50');

            $t->column('References.Primary')
                ->long_text()
                ->title('Primary<br/> reference', "Original source");

            $t->column('References.Secondary')
                ->long_text()
                ->title('Secondary<br/> reference', "Source of input into databse if different from original");

            $t->datasource($data['active_interactions']);

            echo $t->html();
        ?>
    </div>
        <?php endif ?>
</div>
</div>