<?php

namespace App\Mcp\Tools;

use App\Models\Structure;
use App\Services\Structures\Structure3dMolfile;
use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\ResponseFactory;
use Laravel\Mcp\Server\Attributes\Description;
use Laravel\Mcp\Server\Attributes\Name;
use Laravel\Mcp\Server\Tool;
use Laravel\Mcp\Server\Tools\Annotations\IsIdempotent;
use Laravel\Mcp\Server\Tools\Annotations\IsReadOnly;

/**
 * Mirrors GET /api/v1/structures/{identifier}/molfile (StructureController::molfile).
 */
#[Name('get-structure-molfile')]
#[Description('Get the 3D structure of a MolMeDB molecule as an MDL molfile (V2000), generated by RDKit from its SMILES on the first request.')]
#[IsReadOnly]
#[IsIdempotent]
class GetStructureMolfileTool extends Tool
{
    public function handle(Request $request, Structure3dMolfile $molfiles): Response|ResponseFactory
    {
        $validated = $request->validate([
            'identifier' => ['required', 'string', 'max:30'],
        ]);

        $structure = Structure::where('identifier', $validated['identifier'])->first();

        if (! $structure) {
            return Response::error('Structure not found.');
        }

        $molfile = $molfiles->of($structure);

        if ($molfile === null) {
            return Response::error('The 3D structure could not be generated.');
        }

        return Response::structured([
            'identifier' => $structure->identifier,
            'format' => Structure3dMolfile::CONTENT_TYPE,
            'molfile' => $molfile,
        ]);
    }

    /**
     * @return array<string, JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'identifier' => $schema->string()
                ->description('The structure\'s public identifier, e.g. "MM00040".')
                ->required(),
        ];
    }
}
