---
title: Structures
position: 1
---
@php($pages = $docs->pageLimits())
A structure is one molecule or one form of it. It is identified by its MolMeDB identifier (for example `MM00040`) and described by its canonical SMILES, InChI and InChIKey, molecular weight, LogP and links to other databases (PubChem, ChEMBL, ChEBI, DrugBank, PDB ligands). Structures still being curated have no identifier yet and are not public.

## Finding structures

`GET /structures` combines these searches; every result has the identifier needed by the other endpoints.

- **By name or identifier**: `query` matches names and identifiers of other databases.
- **By structure**: `smiles` finds the same molecule written in any SMILES notation; `substructure` finds every structure containing the given one. The substructure search compares chemical structures and has a stricter [rate limit](/docs/rest).
- **By InChIKey**: `inchikey` must match exactly.
- **By an identifier of another database**: `pubchem`, `chembl`, `chebi` (with or without the `CHEBI:` prefix), `drugbank` and `pdb` (a PDB ligand code, such as `CFF`).
- **Several structures at once**: `identifiers` takes up to {{ $pages['identifiers'] }} MolMeDB identifiers separated by commas.

## Forms and parent

Measurements often concern a particular form of a molecule, such as an ionization state or a stereoisomer. Such a form is a structure of its own, identified as `<identifier>.<n>` (`MM00045.2`). The detail of a molecule lists its forms in `forms`, and the detail of a form links its molecule in `parent`.

## Similar structures

`GET /structures/{identifier}/similar` finds structures with a similar chemical structure, most similar first. The similarity is the Tanimoto coefficient of their molecular fingerprints (computed by the Bingo cartridge), from 0 to 1, returned in `similarity`. The default threshold is {{ $pages['similarity_threshold']['default'] }}; the lowest allowed is {{ $pages['similarity_threshold']['min'] }}, below which the similarity is too weak to be useful. Fingerprints do not distinguish every detail of a structure, so even different molecules can have a similarity of 1.

This search has a stricter [rate limit](/docs/rest) and returns at most {{ $pages['similar_structures'] }} structures per page.

## 3D structure

`GET /structures/{identifier}/molfile` returns the 3D structure as an MDL molfile (`chemical/x-mdl-molfile`). It is generated by [RDKit](https://www.rdkit.org) from the SMILES on the first request and stored, so it is meant for visualization and as a starting geometry, not as an optimized conformation.

## Endpoints

@include('docs::_partials.endpoints', ['endpoints' => $docs->endpoints('structures', 'structures/{identifier}', 'structures/{identifier}/stats', 'structures/{identifier}/similar', 'structures/{identifier}/molfile', 'structures/{identifier}/interactions/passive', 'structures/{identifier}/interactions/active')])
The interaction listings of a structure take the same filters as [`/interactions`](/docs/rest/interactions).
