<div  style='text-align: center'>
    <h2>Enum types settings</h2>
</div>

<?= $nonsec_navigator ?>
<div style="margin-bottom: 20px;"></div>

<div class="col-md-12 content">
    <h4><b>Enum types</b></h4>
    <div class="col-md-6">
        <?= $nonsec_enum_types ?>
    </div>
    <div class="col-md-6">
        <?= $nonsec_items ?>
    </div>
</div>


<script src="js/system_enum_types.js?ver=<?=JS_VERSION?>">
    
</script>