<!-- FILTER -->
<form method="get">
<div style="display:flex; flex-direction:column; justify-content:center; align-items:flex-start; margin-bottom: 40px;">
    <h3><b>Filters</b></h3>
    <h4>Status</h4>
        <div style="display: flex;">
            <?php foreach(Run_cosmo::get_all_status() as $id => $label) : ?>
                <input type="checkbox" <?= is_array($params->status) && in_array($id, $params->status) ? 'checked' : '' ?> name="status[]" class="btn-check" value="<?= $id ?>" id="btn-check-status-<?=$id ?>" autocomplete="off">
                <label class="btn-2 btn-outline-secondary<?= is_array($params->status) && in_array($id, $params->status) ? '-active' : '' ?>" for="btn-check-status-<?=$id ?>"><?= $label ?></label>
            <?php endforeach ?>
        </div>
        <h4>State</h4>
        <div style="display: flex;">
            <?php foreach(Run_cosmo::get_all_states() as $id => $label) : ?>
                <input type="checkbox" <?= is_array($params->state) && in_array($id, $params->state) ? 'checked' : '' ?> name="state[]" value="<?= $id ?>" class="btn-check" id="btn-check-state-<?=$id ?>" autocomplete="off">
                <label class="btn-2 btn-outline-secondary<?= is_array($params->state) && in_array($id, $params->state) ? '-active' : '' ?>" for="btn-check-state-<?=$id ?>"><?= $label ?></label>
            <?php endforeach ?>
        </div>
        <h4>Search</h4>
        <div style="display: flex; flex-direction: row; justify-content: flex-start;">
            <input class="searchEngine" value="<?= $params->compound ?>" style="width:400px;" type="text" name="compound" placeholder="Search compound [name, identifier, ...]" id="compoundSearch"><button type="submit" class="btn btn-sm btn-success">Search / Submit filters</button>
        </div>
    </div>
</form>
<div class="action-bar">
    <div>
        <button class="btn btn-sm btn-info"><a href="/validator/add_cosmo_smi"> Add new dataset</a></button>
    </div>
</div>
<script>
    $('.btn-check').change(function() {
        if(this.checked)
        {
            $('label[for="' + this.id + '"]').removeClass('btn-outline-secondary');
            $('label[for="' + this.id + '"]').addClass('btn-outline-secondary-active');
        }
        else
        {
            $('label[for="' + this.id + '"]').removeClass('btn-outline-secondary-active');
            $('label[for="' + this.id + '"]').addClass('btn-outline-secondary');
        }
    })
</script>

 <div class="tab_detail" id="tab_transporters">
    <h3 style="text-align: center;"><b>Scheduled jobs</b> (<?= $total ?>)</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Fragment</td>
                <td>Compound</td>
                <td>Status</td>
                <td>State</td>
                <td>Last update</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($jobs as $j): ?>
            <tr>
                <td style="display: flex; justify-content: center;">
                    <div><?= $j->id_fragment ?></div>
                    <div class="onHover_parent">
                        <span class="onHover_sign glyphicon glyphicon-picture" style="top: 5px; right: -15px;"></span>
                        <span class="onHover" data-endpoint="fragments/structure" data-get="id=<?= $j->id_fragment ?>"></span>
                    </div>
                </td>
                <td><?php $inst = new Run_cosmo(); $f = new Fragments($j->id_fragment); $c = $f->assigned_compound(); echo $c->id ? "<a target='_blank' href='/mol/$c->identifier'>$c->identifier</a>" : '' ?></td>
                <td><?= $inst->get_enum_status($j->status) ?></td>
                <td><?= $inst->get_enum_state($j->state, True) ?></td>
                <td><?= date("d. m. Y", strtotime($j->last_update)) ?></td>
                <td>
                    <a href="/validator/cosmo_detail/<?= $j->id_fragment ?>" title="Detail"><span style="cursor:pointer;" class="glyphicon glyphicon-eye-open"></span></a>
                    <a title="Remove job"><span style="cursor:pointer;" onclick="alert_window('Do you really want to delete the record?', 'delete/cosmo_job/<?= $j->id ?>');" class="glyphicon glyphicon-trash"></span></a>
                    <?php if($j->status == Run_cosmo::STATUS_ERROR) : ?>
                    <a href="/validator/force_cosmo_run/<?= $j->id_fragment ?>?redirection=<?= Url::current() ?>" title="Recompute all"><span style="cursor:pointer;" class="glyphicon glyphicon-repeat"></span></a>
                    <?php endif ?>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
 </div>