<button class="btn btn-success disabled btn-block"><b><span class="glyphicon glyphicon-upload"></span>   Energy file uploader</b></button>
<div><?=$nonsec_navigator?></div>

<div class="col-md-12">
    <div class="col-md-5 col-sm-12 uploadTableDiv">
        
        <form method="post" class="form-group-sm" enctype="multipart/form-data">
            <table class="uploadTable">
                <tr>
                    <td><b>Method:</b></td>
                    <td>
                        <select name="id_method">
                            <?php foreach($methods as $m) : ?>
                            <option class="form-control" value="<?= $m->id?>"><?= $m->name ?></option>
                            <?php endforeach?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><b>Membrane:</b></td>
                    <td>
                        <select name="id_membrane">
                            <?php foreach($membranes as $m) : ?>
                            <option class="form-control" value="<?= $m->id ?>"><?= $m->name ?></option>
                            <?php endforeach?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td><b>Select file to upload: [.csv]</b></td> 
                    <td><input type="file" name="file" id="fileToUpload"></td>
                </tr>
                <tr><td><b>Example</b></td>
                    <td><a href="files/examples/energyFile_example.csv">Download</a></td>
                </tr>
            </table>
            <button style="margin-top:20px;" type="submit" class="btn btn-primary btn-sm pull-right">Upload</button>
        </form>
        
    </div>
    <div class="col-md-2"></div> 
    
</div>

<!-- LIST OF UPLOAD QUEUE -->
<div class="col-md-12 content">
    <div class="tab-contents">
        <div id="tab_interactions" class="tab_detail">
            <h3 style="text-align: center;"><b>Upload queue</b></h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td align="center"><b>Actions</b></td>
                        <td><b>ID</b></td>
                        <td><b>State</b></td>
                        <td><b>File</b></td>
                        <td><b>Membrane</b></td>
                        <td><b>Method</b></td>
                        <td><b>Datetime</b></td>
                    </tr>
                </thead>
                <tbody>
                    <?php $i = 0;
                    foreach ($queue as $q) : ?>
                        <?php $membrane = new Membranes($q->params ? $q->params->membrane : null) ?> 
                        <?php $method = new Methods($q->params ? $q->params->method : null) ?> 

                        <tr>
                            <td align="center">
                                <?php if($q->state === $q::STATE_PENDING) : ?>
                                    <span title="Cancel" onclick="alert_window('Are you sure you want to cancel the process (ID = <?= $q->id ?>)?', 'upload/cancel/<?= $q->id ?>?redirection=upload/energy', false)" style="text-align: center; color: red; cursor:pointer;" class="glyphicon glyphicon-remove"></span>
                                <?php elseif($q->state === $q::STATE_CANCELED) : ?>
                                    <span title="Queue up" onclick="alert_window('Are you sure you want to requeue the process? (ID = <?= $q->id ?>)?', 'upload/requeue/<?= $q->id ?>?redirection=upload/energy', false)" style="text-align: center; color: orange; cursor:pointer;" class="glyphicon glyphicon-inbox"></span>
                                <?php endif ?>
                            </td>
                            <td><?= $q->id ?></td>
                            <td><?= $q->get_enum_state() ?></td>
                            <td><?= $q->file ? '<a href="/export/uploadFile/' . $q->file->id . '">'. $q->file->name . '</a>' : null ?></td>
                            <td><?= $membrane->name ?></td>
                            <td><?= $method->name ?></td>
                            <td><?= $q->create_date ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
