<button class="btn btn-success disabled btn-block"><b><span class="glyphicon glyphicon-upload"></span>   Membrane uploader</b></button>
<div><?=$nonsec_navigator?></div>

<div class="col-md-12 col-sm-12 uploadTableDiv">
    <form method="post">
        <div class="col-md-4">
            <table class="uploadTable" style="margin-top: 38px;">
                <tr>
                    <td><b>Name</b></td>
                    <td><input type="text" class="form-control" name="membrane_name" value="<?= $form_data->membrane_name ?>" required/></td>
                </tr>
                <tr>
                    <td><b>Keywords</b></td>
                    <td><input class="form-control" type="text" value="<?= $form_data->membrane_keywords ?>" name="membrane_keywords"/></td>
                </tr>
                <tr>
                    <td><b>CAM (ID)</b></td>
                    <td><input class="form-control" type="text" name="membrane_CAM" value="<?= $form_data->membrane_CAM ?>" required/></td>
                </tr> 
            </table>
        </div>

        <div class="col-md-8">
            <div class="textfield">
                <h5><b>Description</b></h5>
                <textarea name="membrane_descript"><?= $form_data->membrane_descript ?></textarea>
            </div>
            <div>
                <h5><b>References</b></h5>
                <textarea name="membrane_references"><?= $form_data->membrane_references ?></textarea>
            </div>
        </div>
        <button style="margin:20px;" class="btn btn-success pull-right">Save</button>
    </form>
</div>
   
 <script>
    CKEDITOR.replace( 'membrane_descript' );
    CKEDITOR.replace( 'membrane_references' );
</script>